name: Deploy to Render
run-name: Deploying to Render
on:
  push:
    branches:
      - master

jobs:
  Deploy-to-Render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update environment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          PORT: ${{ secrets.PORT }}
        run:  |
              curl  --request PUT \
                    --url "https://api.render.com/v1/services/$RENDER_SERVICE_ID/env-vars" \
                    --header "accept: application/json" \
                    --header "authorization: Bearer $RENDER_API_KEY" \
                    --header "content-type: application/json" \
                    --data "[{\"key\": \"PORT\",\"value\": \"$PORT\"}]"
      - name: Trigger Render deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run:  |
              curl  --request POST \
                    --url "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
                    --header "accept: application/json" \
                    --header "authorization: Bearer $RENDER_API_KEY" \
                    --header "content-type: application/json" \
